### ISSUE TITLE
Title bar missing Issue in onboarding screens

### ISSUE THREAD

**Issue by siddique26** [maidsafe/safe-network-app#102]
The following Figma File links to the detailing of the issue.
Hit 'C' for comments to view the issue details and discussions.

https://www.figma.com/file/53iCtsVlxk9S0N9fAGJ5nH/Safe-Network-App-v1?node-id=1939%3A187

**Comment by calumcraig** [comment]
Testing on latest master: `b061d4e (HEAD -> master, origin/master, origin/HEAD) Merge pull request #114 from shankar2105/style_issues`

Onboarding screens:
![image](https://user-images.githubusercontent.com/44327924/65026649-e2e7a400-d930-11e9-8df8-a594c2a48ea4.png)
![image](https://user-images.githubusercontent.com/44327924/65026676-f3981a00-d930-11e9-96bd-42dcd3ad442b.png)
![image](https://user-images.githubusercontent.com/44327924/65026711-014d9f80-d931-11e9-9fc8-d7f13077f1e8.png)
