### ISSUE TITLE
Basic windows setup

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#12]
- [x]  Setup standard window with fixed width & height.
- [x] Setup tray window with fixed width & non-fixed height. After a max height of 400px it should start scrolling.
- [x] Implement action to switch between standard and tray window.
- ~[ ] Disable this switching between windows while on on-boarding screen.~
- [x] Create generic page component which is responsive to fit both standard and tray window, so the switch from one another doesn't affect the layout.
- [x] Setup application main menu for standard window.
- [x] Write unit test cases.
- ~[ ] Write e2e tests.~

----

Edited as per [comment](https://github.com/maidsafe/safe-network-app/issues/12#issuecomment-510280875)

**Comment by joshuef** [comment]
Yeh, I'd say we can leave those out of this issue. And call this done if you're happy for a last review

**Comment by safesurfer** [comment]
QA verified, and confirming switching between standard window and tray window by clicking switch button.
