### ISSUE TITLE
Click back on setting menu takes user to main menu

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-network-app#120]
**Steps to reproduce:**
1. Click on "About application" option from an application meatball menu of main screen to enter manage application screen
2. Click on cog button to enter setting screen
3. Click on back arrow of settings screen

**Expected:**
User is returned to manage application screen (ie where they came from).
**Actual:**
User is taken to the main SNAPP screen.

**Comment by joshuef** [comment]
@manavbp we should really just be using the back button as a navigation tool, so it should literally send the user back a path (ie not hardcoded in any way). We can use the history and `withRouter` component from `react-router` here.

**Comment by manavbp** [comment]
Actually @joshuef the settings icon in application Detail page has been removed based on the figma design and replaced with the meatball Menu instead. But making use of the `navigation tool` I agree is better than hardcoding it. I'll create separate issue for that now.

**Comment by manavbp** [comment]
Closing this issue as its irrelevant now atm moment based on the new figma design
