### ISSUE TITLE
On-Boarding process should open in standard window only

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#121]
- [x] Need to ensure that on-boarding process opens only in standard window mode and not in tray mode.
- [x] Write unit test cases
- [x] Write write e2e tests

**Comment by calumcraig** [comment]
Testing v0.0.3 RC1.

macOS:
![Screenshot from 2019-10-09 09-23-04](https://user-images.githubusercontent.com/44327924/66464300-9fd3a900-ea76-11e9-8697-c82a093f5c6a.png)

Linux:
![image](https://user-images.githubusercontent.com/44327924/66464414-dad5dc80-ea76-11e9-826f-2c6cbbe76d4b.png)

Windows:
![image](https://user-images.githubusercontent.com/44327924/66464906-c9410480-ea77-11e9-9834-0ca9d33a3b04.png)

Moving this to done.
