### ISSUE TITLE
Implement On-Boarding wizard view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#13]
- [x] Skip if user already went through the on-boarding process 
- [x] Implement navigation controls to go forward and backward the wizard
- [x] Implement the on-boarding screens
- [x] If application got closed/ crashed without completing the on-boarding screen, then it should start from the first page.
- [x] Even after updating to a new version, the application should skip this on-boarding screens on start.
- [x] Write unit test cases
- [x] Write e2e tests

> Note: Basic settings not a part of this task

**Comment by hunterlester** [comment]
Important note for QA on Linux: It's not possible to observe on-boarding UI as the associated action creator depends on locally saved user preferences, which won't save at the moment until we work around file permission issue.
See: https://github.com/maidsafe/safe-network-app/pull/32/files#diff-81de088ebb378156b16b369c9a4e6f1dR58

**Comment by hunterlester** [comment]
However, will be resolved once #38 is merged.

**Comment by safesurfer** [comment]
QA verified
