### ISSUE TITLE
Remove / disable non applicable settings options

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-network-app#147]
There are currently a number of options found in the settings menu:

![image](https://user-images.githubusercontent.com/44327924/66116928-7a085900-e5cb-11e9-8c58-9906dd730d02.png)

However, most of them are currently non functional and will be implemented in future releases.

Can we remove or disable the ones that are currently not working?

**Comment by calumcraig** [comment]
Testing on latest master: `8442234 (HEAD -> master, origin/master, origin/HEAD) tests(e2e): fix e2e settings page tests` 

Linux:
The unused settings have been removed from the options page:
![image](https://user-images.githubusercontent.com/44327924/66209003-68e44880-e6ae-11e9-979c-0bbb28301fa7.png)

**Comment by calumcraig** [comment]
However, the non applicable settings can still be seen on the initial set up screen:
![image](https://user-images.githubusercontent.com/44327924/66210223-3851de00-e6b1-11e9-8fda-4b06ab7840d5.png)

**Comment by safesurfer** [comment]
QA verified on Windows.

**Comment by calumcraig** [comment]
Confirmed that the unused options have now been removed from the splash screen too:

![image](https://user-images.githubusercontent.com/44327924/66494764-13de7300-eab0-11e9-82a7-e1813bbfb0c4.png)

 (On Linux).

**Comment by calumcraig** [comment]
![image](https://user-images.githubusercontent.com/44327924/66495822-cb27b980-eab1-11e9-9bd8-2df269792fc7.png)

macOS.
