### ISSUE TITLE
Implement Error/Warn/Info banners

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#15]
- [x] Implement Ui for Error or Warn or Info banner to open on top of application list
- [x] Implement action to add and dismiss notification
- [x] Handle multiple banner and popup based on it priority
- [x] Add IPC for restart System
- [x] Add IPC for Close App
- [x] Write unit test cases
- [x] Write e2e tests

**Comment by safesurfer** [comment]
QA verified
