### ISSUE TITLE
Misspelling of "your"

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-network-app#156]
1. Launch SNAPP.
2. Disconnect from internet.
3. Attempt to install a SAFE app

Expected:
"_Your_ internet connection"
Actual:
"Oh no! _You're_ Internet connection is down!"
![image](https://user-images.githubusercontent.com/44327924/66219653-7821c100-e6c3-11e9-954e-e2da5e2cc59c.png)

**Comment by dotcomboom** [comment]
Made a PR for this: https://github.com/maidsafe/safe-network-app/pull/157

**Comment by 2secslater** [comment]
@joshuef Can this bug please be closed now?
