### ISSUE TITLE
Implement meatball menu component

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#16]
- [x] Implement meatball menu component to render dynamic data based on its parent component state
- [x] Write unit test cases
- [x] Write e2e tests

**Comment by safesurfer** [comment]
Clicking meatball menu (isn't it kebab menu???) expands the menu that contains options for about the app and install the app. Though the menu component is implemented, the functioning of the menu items are still in progress when it is tested.

**Comment by hunterlester** [comment]
@safesurfer Right, they won't be functional until applications can be installed, uninstalled, updated, etc.
