### ISSUE TITLE
Fetch & render application list

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#17]
- [x] Host the application list on Github repository
- [x] Implement action to fetch the application list and render it
- Show developer apps if enabled in basic settings or else hide them
- [x] Parse and check the application list data
- [x] This should fit both standard and tray window
- [x] Apply meatball menu to the list and dynamically change based on list state
- [x] Handle error cases like
  - [x] Unable to connect to internet
  - [x] Unable to connect to Github server
  - [x] Application list data not found
  - [x] Application list data corrupted
- [x] Write unit test cases

Dependency tasks
---
#15 and #16

**Comment by joshuef** [comment]
QA: To check that this is being pulled, you can see if there is only the `Safe Browser` app listed. This means that the applist has been pulled from the server (as the defaults include a second dummy app)

**Comment by calumcraig** [comment]
The first point described above has been superseded. The application list is now hosted on AWS S3 at https://safe-network-app.s3.eu-west-2.amazonaws.com/managedApplications.json

**Comment by calumcraig** [comment]
After revoking public access to `managedApplications` SNApp is unable to retrieve the list of applications (the previous two are displayed from running prior - TBC).
![image](https://user-images.githubusercontent.com/44327924/64627833-3ebda480-d3e8-11e9-95ed-c7c577d7f84f.png)

**Comment by calumcraig** [comment]
Raised issue https://github.com/maidsafe/safe-network-app/issues/122 regarding the error message above.

**Comment by calumcraig** [comment]
Then edited the `managedApplications.json` to include reference to another dummy application:
![image](https://user-images.githubusercontent.com/44327924/64685965-cacedb00-d47f-11e9-9467-571440f14917.png)

**Comment by calumcraig** [comment]
And restored the application list to its original state:
![image](https://user-images.githubusercontent.com/44327924/64686620-d79ffe80-d480-11e9-8233-ca70efc47e16.png)

**Comment by calumcraig** [comment]
The meatball menu for various states for the boilerplate app:
Not installed:
![image](https://user-images.githubusercontent.com/44327924/64686753-10d86e80-d481-11e9-9cb0-0e4741a7424b.png)
During install:
![image](https://user-images.githubusercontent.com/44327924/64686771-22217b00-d481-11e9-9d11-be93976a3c11.png)
Whilst install is paused:
![image](https://user-images.githubusercontent.com/44327924/64686802-2f3e6a00-d481-11e9-83ad-28bc7ff8d5ba.png)
Install has completed - app is installed:
![image](https://user-images.githubusercontent.com/44327924/64686837-3feee000-d481-11e9-8302-7050426baee3.png)

**Comment by calumcraig** [comment]
All the error cases are handled by the same error message as seen above:

- Unable to connect to internet
- Unable to connect to Github server (S3)
- Application list data not found
- Application list data corrupted

![image](https://user-images.githubusercontent.com/44327924/64687692-e982a100-d482-11e9-8475-f09dc337a66c.png)

**Comment by calumcraig** [comment]
QA verified, moving to done.
