### ISSUE TITLE
Implement Application detail view

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#18]
- [x] Implement application detail view page component
- [x] Check this fits both standard and tray view
- [x] Implement a link to application detail view from application list
~Implement action to fetch application's Latest Update data from application release server and render it. Also handle its error cases.~
- [x] Apply meatball menu component to it and dynamically change based on application detail view state
- [x] Write unit test cases

### Requires
- To host application latest update on release server

**Comment by joshuef** [comment]
Reference:
https://www.dropbox.com/s/1vl2f0r3sy3sl0q/Screenshot%202019-08-05%2009.49.52.jpg?dl=0

**Comment by joshuef** [comment]
@manavbp FYI, i'll make a new issue for: 
>- [ ] Implement action to fetch application's Latest Update data from application release server and render it. Also handle its error cases.

**Comment by safesurfer** [comment]
QA verified that the application details have been implemented and they look fine on both standard and tray windows.
