### ISSUE TITLE
Application installation

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#20]
- [x] Implement installation component
- [x] This includes different states of installation
  - [x] Install
  - [x] Downloading
  - [x] Pause downloading
  - [x] Resume downloading
  - [x] Uninstall (pending/success/fail)
  - [x] Download cancel
  - [x] Download error
    ~~- [ ] If the system space if full during download, user should be thrown a clear up some space notification and then we should resume the download~~ Currently there's no way to get this erroe (that I can see). We can have this as an enhancement down the line.
  - [x] Installation
  - [x] Cancel installation
  - [x] Retry installation (via notification)
  - [x] Installation error
  - [x] Installation success
  ~- [ ] UpdateApplication~
  ~- [ ] discern state of update vs/ installed for existing apps.~
- [x] Implement action to update progress and handle installation success and failure on UI
- [x] Write unit test cases
- [x] Write e2e test cases
- [x] Flag installed apps as such from local fs

**Comment by joshuef** [comment]
I've updated original to not include updates at the moment. They can come as a separate PR when we've auto-update setup in browser eg.

**Comment by calumcraig** [comment]
Install
![image](https://user-images.githubusercontent.com/44327924/64698998-d3350f00-d49b-11e9-8ee7-ca93b54bd446.png)
Downloading
![image](https://user-images.githubusercontent.com/44327924/64699035-dfb96780-d49b-11e9-91a2-3bd15fbc5d0b.png)
Pause downloading
![image](https://user-images.githubusercontent.com/44327924/64699053-e942cf80-d49b-11e9-9f81-0bd80642c60f.png)
Resume downloading
![image](https://user-images.githubusercontent.com/44327924/64699071-f233a100-d49b-11e9-90b4-3a8c77626681.png)
Uninstall (pending/success/fail)
![image](https://user-images.githubusercontent.com/44327924/64699098-fcee3600-d49b-11e9-89a2-ff922731d418.png)
Download / install cancel
![image](https://user-images.githubusercontent.com/44327924/64699125-07103480-d49c-11e9-928e-d5633502cf16.png)
Download / install error
![image](https://user-images.githubusercontent.com/44327924/64699200-2f982e80-d49c-11e9-8319-7536eda08e7d.png)
Installation
Retry installation (via notification)
![image](https://user-images.githubusercontent.com/44327924/64699230-3f177780-d49c-11e9-8738-f654beb5a120.png)
Installation success
![image](https://user-images.githubusercontent.com/44327924/64699243-476fb280-d49c-11e9-9671-6f637b3213cb.png)

**Comment by calumcraig** [comment]
QA verified, moving this to done.
