### ISSUE TITLE
Open browser button doesn't do anything Win 10

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe-network-app#214]
Downloaded the Windows version of the app and installed it (I already had the previous version installed but I installed 0.0.4 fresh). Downloaded and installed the browser (0.15.2) from the App.

## Expected Behavior
After installation the Open button opens the browser

## Current Behavior

Nothing happens, but I can open the browser from the appdata/roaming/SAFE Network App/downloads folder.

## Your Environment

- Node version : N/A
- Version or Branch used : SAFE Network App 0.0.4  download
- Operating System and version : Win 10
- Link to your project : N/A

**Comment by joshuef** [comment]
thanks @JPL1 will dig in here monday. 👍

**Comment by joshuef** [comment]
@JPL1 latest alpha should have this sorted 👍 : https://github.com/maidsafe/safe-network-app/releases/tag/v0.0.5-alpha.20

**Comment by JPL1** [comment]
Yes working now - I had to uninstall all previous versions first though otherwise it was trying to update and getting stuck.
