### ISSUE TITLE
Auto update not restarting fully - update does not complete (0.0.4 -> 0.0.5)

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-network-app#226]
Found on macOS 10.15.2 while updating from 0.0.4 --> 0.0.5.

Seems related to or a recurrence of #215 

Steps to reproduce:
1. Launch old version of app (e.g. 0.0.4)
2. When prompted to "Restart Now" to install update click to restart.

Expected result:
App should restart and should be updated to the latest version (0.0.5) when it reopens.

Actual result:
App at first appears to close, but then does not reopen.
On closer inspection the app icon in the macOS Dock still has a dot under it, indicating that the app never closed fully.
On clicking to bring up the app and then checking the app version, it is still the old version (0.0.4).
If I then fully close & reopen the app manually it opens the new version (0.0.5)

**Comment by joshuef** [comment]
@S-Coyle makes sense that 0.4 wouldn't work as it doesn't have the commit yet.

So I think the test for this will be 0.5->0.6 updates. (Or 0.5 alpha->0.5 real). 

Will leave this here to track

**Comment by S-Coyle** [comment]
Tested updating from v0.0.5-alpha to latest v0.0.5, and from v0.0.5-beta to latest v0.0.5 and the "Restart Now" option worked fine on both of these, so closing this issue as verified it is resolved from v0.0.5 onwards
