### ISSUE TITLE
GitHub Action for pushing release files to S3 is not working

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-network-app#227]
This did work previously, but now results in the error:
```
##[warning]Failed to download action 'https://api.github.com/repos/actions/aws/tarball/master'. Error Response status code does not indicate success: 404 (Not Found)
```

For example of failure see:
- https://github.com/maidsafe/safe-network-app/commit/7bee40e17bc35cda70d9dddbcfda3e9a0048f526/checks?check_suite_id=412430509#step:1:10

**Comment by joshuef** [comment]
seems like s3 is now installed by default: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

**Comment by joshuef** [comment]
This should be sorted via updated actions from browser
