### ISSUE TITLE
E2E tests for window visibility logic

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe-network-app#36]
This application consists of two `BrowserWindow` instances.

One for the [standard](https://github.com/maidsafe/safe-network-app/blob/master/app/setupLaunchPad.ts#L130) window and one for the [tray window](https://github.com/maidsafe/safe-network-app/blob/master/app/setupLaunchPad.ts#L196), which emulates a tray menu cross-platform.

The user has the ability to switch between the two windows, for which this application needs e2e tests to catch any breaking of the logic which handles this behavior.

Needs tests for the following behavior:
- [ ] Standard window is `visible` -> user clicks `Switch` button -> standard window should `hide` -> tray window should be `visible` -> user clicks on `Switch` button -> standard window should be `visible` -> tray window should `hide`.
- [ ] Standard window is `visible` -> user clicks on another window in their desktop -> standard window should `blur`
- [ ]  Linux OR macOS -> standard window is `visible` -> user clicks on tray icon -> chooses menu item with application name -> standard window should `hide` -> user clicks on tray icon -> chooses menu item with application name -> standard window should be `visible`
- [ ]  Windows OS -> standard window is `visible` -> user clicks on tray icon -> standard window should `hide` -> user clicks on tray icon -> standard window should be `visible`

- [ ] Tray window is `visible` -> user clicks `Switch` button -> tray window should `hide` -> standard window should be `visible` -> user clicks `Switch` button -> tray window should be `visible` -> standard window should `hide`.
- [ ] Tray window is `visible` -> user clicks on another window in their desktop -> tray window should `hide`, emulating tray menu behavior.
- [ ] Linux OR macOS -> tray window is `visible`  -> user clicks on tray icon -> chooses menu item with application name -> tray window should `hide` -> user clicks on tray icon -> chooses menu item with application name -> tray window should be `visible`
- [ ]  Windows OS -> tray window is `visible` -> user clicks on tray icon -> tray window should `hide` -> user clicks on tray icon -> tray window should be `visible`

- [ ] User clicks on tray icon -> chooses `Exit` option -> application process will quit, closing any `visible` window

- [ ] macOS -> Standard window is `visible` -> user clicks on dock icon -> chooses `hide` option -> standard window should `hide`
- [ ] macOS -> Standard window is `visible` -> dock icon should be `visible` -> user clicks `Switch` button -> standard window should `hide` -> tray window should be `visible` -> dock icon should `hide`
- [ ] macOS -> tray window is `visible` -> dock icon is `hidden` -> user clicks `Switch` button -> standard window should be `visible` -> tray window should `hide` -> dock icon should be `visible`

This is not yet an exhaustive list. Please add any missing expected behavior.
Something to be aware of, and which needs to be documented are the differences in visibility events, cross-platform.
For example, on Linux, when a window hides, solely the `hide` event is triggered, whereas on macOS, both the `hide` and `blur` events are triggered. The order of the events can also be different depending on the case.

**Comment by hunterlester** [comment]
Currently unable to implement e2e tests with TestCafe as it doesn't recognize secondary window when instructed to click on `Switch` button.

I'm hoping that Spectron makes these e2e tests possible.

**Comment by hunterlester** [comment]
First step is to write a few e2e tests, don't start out exhausting the above list, to see if they test windows visibility properly, then to determine if the tests are stable on Travis.

**Comment by calumcraig** [comment]
Moving this to done.
