### ISSUE TITLE
Debug electron-db issue on Linux

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe-network-app#37]
On Linux, this is not a file permission issue as I previously though, it looks more like `electron-db` is using the wrong path when it's API methods are called without a custom location.

So an application folder IS indeed successfully saved `/home/hunterlester/.config/Electron/safe-launchpad`
However, `electron-db` is attempting to create table at `/var/local/safe-launchpad/userPreferences.json`.

**Comment by joshuef** [comment]
Should this actually involve a PR to electron-db to fix this? Or is that correct behaviour for them?

**Comment by safesurfer** [comment]
Since it is irrelevant PR for now, moving it to done
