### ISSUE TITLE
Window switching bugs

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe-network-app#39]
Current behavior is for the application to initialize two windows. One for the emulated tray window and one for the standard window. The user can then click on a `Switch` button in order to toggle between the two windows.

It seems to be causing a few important issues though.

I'm thinking about resolving this by initializing only one of the windows and when the user switches to the other window, destroy the the previous window and create a new window.

**Comment by safesurfer** [comment]
I'm able to switch between two windows, (tray window and standard window) when I click switch button and confirming one window exists at a time.
