### ISSUE TITLE
Organise App List Publication w/ DO/S3

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-network-app#50]
We need a URL to pull the latest application list from.

This should likely be outwith of this repo.

cc @S-Coyle

**Comment by S-Coyle** [comment]
@joshuef I'll upload the file you need to s3 and provide the link - let me know when you have the file

**Comment by joshuef** [comment]
@S-Coyle can you upload: https://raw.githubusercontent.com/maidsafe/safe-network-app/master/app/managedApplications.json

FYI this file could/would change with releases to our applications eventually. So we should probably plan to have that integrated into CI workflow down the line. (Though for now manual is more than enough as it wont really change until we release this app)

**Comment by S-Coyle** [comment]
Uploaded to s3 and sent link to @joshuef

**Comment by calumcraig** [comment]
List of applications is now hosted on AWS S3, via the `managedApplications.json` file;

https://safe-network-app.s3.eu-west-2.amazonaws.com/managedApplications.json

**Comment by calumcraig** [comment]
QA verified, moving to done.
