### ISSUE TITLE
MacOS Uninstall bug

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-network-app#66]
Right now uninstalling on MacOS (at least for me) is failing due to some dirs being full (`.asar` specifically).

We'll need to wrk out how to handle this

**Comment by calumcraig** [comment]
Testing on `1b3c046 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Update Basic Setting Button text`
I have been able to successfully uninstall both available apps (SAFE Browser and Electron Boilerplate).
QA verified, moving this to done.
