### ISSUE TITLE
Get installed app version

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-network-app#67]
Right now we have no way to get installed application versions.

We need to ensure published applications have their `package.json` _outside_ of the `app.asar` file/folder so it can be easily read by SNAPP.

FYI @manavbp

**Comment by shankar2105** [comment]
This issue got fixed with PR #134 (here https://github.com/maidsafe/safe-network-app/blob/dev/app/manageInstallations/helpers.ts#L102-L131)
