### ISSUE TITLE
Hide tray icon while on standard window mode

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safe-network-app#72]
To hide the tray icon of the application when switched back to the standard window mode.

**Comment by safesurfer** [comment]
Tray icon is hiding when you switch to standard window mode. but I can see two icons on the tray, one of the two icons is hiding and the other one remains same. moving it to in-progress.

**Comment by calumcraig** [comment]
`Pin to Menu Bar` is selected:
![image](https://user-images.githubusercontent.com/44327924/64124001-c7f82a00-cd9d-11e9-8fcc-5911fe925af7.png)
`Pin to Menu Bar` is deselected:
![image](https://user-images.githubusercontent.com/44327924/64124044-e4946200-cd9d-11e9-951d-d38db7ca6dac.png)
Ie, no icons are in the system tray when the app isn't pinned.

**Comment by calumcraig** [comment]
QA verified, moving this to done.
