### ISSUE TITLE
Not able to move the window by dragging, when it is not pinned to tray

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-network-app#74]
Testing it on MacOS. I'm not able to drag the window, when it is detached from the tray by switching off `Pin to Menu Bar`

STR:
1. Open the app
2. Click Settings icon
3. Turn off `Pin to Menu Bar` switch which will detach the window from tray

Expected:
Should be able to move the detached window by click and drag

Actual:
Not able to move the window by dragging it

**Comment by calumcraig** [comment]
Testing on the latest on Master: `1b3c046 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Update Basic Setting Button text`

When `Pin to Menu Bar` is deselected, the app can be dragged anywhere on the desktop:

![image](https://user-images.githubusercontent.com/44327924/64124240-61bfd700-cd9e-11e9-878c-9b3e3634e4c7.png)

![image](https://user-images.githubusercontent.com/44327924/64124322-9c297400-cd9e-11e9-8374-25b0058edbd3.png)

![image](https://user-images.githubusercontent.com/44327924/64124382-d135c680-cd9e-11e9-95c7-a9d36432af12.png)

**Comment by calumcraig** [comment]
QA verified, moving this to done.
