### ISSUE TITLE
Clicking close button does not close standard window and throws error when we try to open it

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-network-app#78]
STR:
1. Open SNAPP
2. Click the gear icon to open settings page
3. Turn off `Pin to Menu bar` switch
4. Click the close button on the standard window
5. Try to open it by clicking the tray icon

Expected:
It should close the window completely.

Actual:
It seems that it closes the window partially, still able to see the icon on the tray. If you click the tray icon, it throws the following error.

![image](https://user-images.githubusercontent.com/27578024/63497530-90f26080-c4e1-11e9-8611-f46256777a17.png)

**Comment by ravinderjangra** [comment]
Also, I wanted to close it and it had no option to close/force close the app

**Comment by calumcraig** [comment]
Testing on latest master: `1b3c046 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Update Basic Setting Button text`

**Comment by calumcraig** [comment]
Launch the SNAPP:
![image](https://user-images.githubusercontent.com/44327924/64123572-ad718100-cd9c-11e9-9071-154489f9d237.png)
Deselect `Pin to Menu Bar`:
![image](https://user-images.githubusercontent.com/44327924/64123627-d4c84e00-cd9c-11e9-8c61-c946182eed8b.png)
Try to close the application;
![image](https://user-images.githubusercontent.com/44327924/64123675-f6293a00-cd9c-11e9-95d2-396ce7b8988b.png)
Application disappears from the desktop. Can still be seen in the docker and not in the system tray:
![image](https://user-images.githubusercontent.com/44327924/64123786-35578b00-cd9d-11e9-93f1-fe4e41044833.png)
![image](https://user-images.githubusercontent.com/44327924/64123819-46080100-cd9d-11e9-9cfc-cf6ab1c5080d.png)

**Comment by calumcraig** [comment]
QA verified, moving to done.
