### ISSUE TITLE
Installing app animation is not in sync with Figma design

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-network-app#81]
Installing app animation is not in sync with Figma design.

![image](https://user-images.githubusercontent.com/27578024/63676104-e3948b00-c807-11e9-843d-9923a0075eaa.png)

**Comment by calumcraig** [comment]
While downloading the SAFE Browser:
![image](https://user-images.githubusercontent.com/44327924/64125172-11964400-cda1-11e9-81fa-4bd0f5150d93.png)

**Comment by calumcraig** [comment]
QA verified, moving this to done.
