### ISSUE TITLE
MacOs 'Getting Started' CSS overflow

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-network-app#86]
now we've the menu bar, the getting started page CSS overflows on the Y axis:

https://www.dropbox.com/s/d9xli99qidarjs5/Screenshot%202019-08-29%2010.16.11.jpg?dl=0

**Comment by calumcraig** [comment]
Testing on `fc1a9c5 (HEAD -> master, origin/master, origin/HEAD) Chore: Fix on-boarding styling issue`

![image](https://user-images.githubusercontent.com/44327924/64188665-be88c380-ce6a-11e9-815e-258baeb17326.png)

![image](https://user-images.githubusercontent.com/44327924/64188701-cc3e4900-ce6a-11e9-8406-15e6cb2c6111.png)

![image](https://user-images.githubusercontent.com/44327924/64188744-dbbd9200-ce6a-11e9-8c27-a93843784a9a.png)

There is no overflow on the y axis now.

**Comment by calumcraig** [comment]
QA verified, moving this to done.
