### ISSUE TITLE
Update wording w/ onboarding settings to 'save' changes rather than apply them now

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-network-app#87]
## Currently: 

Onboarding settings seem as if they should be applied immediately.

## Wanted:

Change wording from `next` to `save` for continue button.

## TODO: 

- [x] Update text

**Comment by calumcraig** [comment]
Testing on latest master: `1b3c046 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Update Basic Setting Button text`

After running `yarn && yarn package` the onboarding screens can be seen:
![image](https://user-images.githubusercontent.com/44327924/64117666-ae4ee680-cd8d-11e9-8d1c-f0ad9326c125.png)

**Comment by calumcraig** [comment]
Wording is to "save" settings.

**Comment by calumcraig** [comment]
Moving this to done.
