### ISSUE TITLE
Handling Download And Install Button States

### ISSUE THREAD

**Issue by manavbp** [maidsafe/safe-network-app#91]
Button States-
- [x] If downloaded and is installing, then should show cancel Install
- [x] If Install error show cancel Install
- [x] If downloading show pause download
- [x] If download paused show continue

**Comment by calumcraig** [comment]
Testing against latest master: `a6ed431 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Handle network disconnection state`

- If downloaded and is installing, then should show cancel Install
App status goes from downloading to "Open"
- If Install error show cancel Install
![image](https://user-images.githubusercontent.com/44327924/64695582-68cca080-d494-11e9-9406-d5fa7bdcddc7.png)
- If downloading show pause download
![image](https://user-images.githubusercontent.com/44327924/64695608-7c780700-d494-11e9-8add-26abc75536bc.png)
- If download paused show continue
![image](https://user-images.githubusercontent.com/44327924/64695642-8a2d8c80-d494-11e9-87f5-2b3e7db60777.png)

**Comment by calumcraig** [comment]
QA verified, moving to done.
