### ISSUE TITLE
cancelling one of two simultaneous installations cancels both operations

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-network-app#95]
**Steps to reproduce:**
1. Select install for more than one application:
![image](https://user-images.githubusercontent.com/44327924/64166022-207f0400-ce3e-11e9-8cb6-8c807fbf0db5.png)
2. Select "Cancel Install" for one application:

**Expected:**
Only the application "cancel install" was selected for will cancel.
**Actual:**
Both install operations are cancelled. An error is thrown:
![image](https://user-images.githubusercontent.com/44327924/64165918-e9a8ee00-ce3d-11e9-9ee0-8716b628b340.png)
![image](https://user-images.githubusercontent.com/44327924/64165935-f4fc1980-ce3d-11e9-9826-0bdd42a0a55e.png)

**Comment by calumcraig** [comment]
Testing on latest master: `a6ed431 (HEAD -> master, origin/master, origin/HEAD) chore(refactor): Handle network disconnection state`
![image](https://user-images.githubusercontent.com/44327924/64690923-7cbed500-d489-11e9-9c50-3e60882182e3.png)

Start installing two applications simultaneously:
![image](https://user-images.githubusercontent.com/44327924/64689922-2c467800-d487-11e9-86c2-b12c0203cb7e.png)
Cancel one instance:
![image](https://user-images.githubusercontent.com/44327924/64690880-5f8a0680-d489-11e9-8ae4-0f59b33ed98b.png)
Still getting the same issue, moving this back to in progress.

**Comment by shankar2105** [comment]
@calumcraig Closing this issue as this is not reproducible.

**Comment by safesurfer** [comment]
This is not reproducible at the moment, since SNApp has only one application in its app list now
