### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by siddique26** [maidsafe/safe-network-app#99]
The following Figma file ( in the GitHub issues page ) contains Styling issues with the SNApp at the moment: 

https://www.figma.com/file/53iCtsVlxk9S0N9fAGJ5nH/Safe-Network-App-v1?node-id=1913%3A27261

- [ ] Text Style ` Body 2 ` missing ( in comments 9, 12, 14, 15, 40, 35, 38, 39 )
- [ ] Text Style `H5` missing ( 10 )
- [ ]  [ ] Text Style `H6` missing ( 13 )
- [ ] On-boarding screens frame is wider ( 36 )
- [ ] Title bar missing in on-boarding screens ( 8 )
- [ ] Primary button needs a minimum width ( 21, 24 )
- [ ] Header and App row needs a fixed height
- [ ] State message needs to be shown in App row while Downloading / Installing
- [ ] Icons doesnt match the size in Figma style
- [ ] Meatball menu pop-up screen needs a fixed width
- [ ] Meatball menu icon to be placed instead of settings icon in  'Manage App screen`
- [ ] Settings icon to be removed in settings page 
- [ ] Padding should be set to 0 for divider in 'Manage App screen'

**Comment by JimCollinson** [comment]
Let's close this issue and break down into more manageable chunks. Perhaps one issue per screen at a minimum.
